name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  statuses: write
  checks: write

env:
  DOCKER_COMPOSE_FILE: infra/docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          cd infra
          docker compose build

      - name: Start services
        run: |
          cd infra
          docker compose up -d

      - name: Wait for gateway to be ready
        run: |
          for i in {1..10}; do
            if docker exec infra-gateway-1 curl -f http://localhost:8000; then
              echo "Gateway is ready";
              exit 0;
            fi;
            echo "Gateway not ready, waiting 5 seconds...";
            sleep 5;
          done;
          exit 1
          
      - name: Run test front-end
        run: docker exec infra-front-end-1 curl -f http://localhost:80 || exit 1
      - name: Run test gateway
        run: docker exec infra-gateway-1 curl -f http://localhost:8000 || exit 1
      - name: Run test essayage
        run: docker exec infra-essayage-1 curl -f http://localhost:8001 || exit 1
      - name: Run test recommendation
        run: docker exec infra-recommandation-1 curl -f http://localhost:8002 || exit 1

      - name: Run unit tests
        run: |
          docker exec infra-essayage-1 pytest /app/tests/unit/ -v

      - name: Save test logs
        if: always()
        run: |
          mkdir -p logs
          docker logs infra-essayage-1 > logs/essayage.log
          docker logs infra-front-end-1 > logs/front-end.log
          docker logs infra-gateway-1 > logs/gateway.log
          docker logs infra-recommandation-1 > logs/recommandation.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: service-logs
          path: logs/
          retention-days: 5

      - name: Cleanup
        if: always()
        run: |
          cd infra
          docker compose down -v

      - name: Create Pull Request to main
        if: github.ref == 'refs/heads/develop'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto update from develop"
          title: "Auto PR: Merge develop into main"
          body: "All tests passed on develop. This PR is automatically generated."
          base: main
          branch: feature/auto-pr-develop-to-main
          delete-branch: true
          draft: false
          force: true
          path: .
          add-paths: .
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>