name: Deploy Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            cd ${SERVER_PATH:-/home/ubuntu/Projet-spe-3} || exit 1
            echo "Pulling latest changes..."
            git pull || exit 1
            cd infra || exit 1
            echo "Stopping existing containers..."
            docker-compose down || true
            echo "Building and starting new containers..."
            docker-compose up --build -d || exit 1
            echo "Waiting for services to be ready..."
            sleep 10
            echo "Checking services health..."
            docker-compose ps
            echo "Deployment completed successfully!"

      - name: Verify Deployment
        uses: appleboy/ssh-action@v0.1.8
        if: success()
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${SERVER_PATH:-/home/ubuntu/Projet-spe-3}/infra
            docker-compose ps --format "{{.Name}}: {{.Status}}"
